name: tplaytv
description: Riya Play Android TV App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  dpad: ^2.0.2
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.3.3
  provider: ^6.1.1
  package_info_plus: ^8.0.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  wakelock_plus: ^1.2.11
  android_intent_plus: ^5.3.0
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  qr_flutter: ^4.1.0
  logger: ^2.5.0
  shimmer: ^3.0.0
  better_player:
    git: https://github.com/Lo4D/better-player-ultra.git
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_iconly: ^1.0.2
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  palette_generator: ^0.3.3+7
  
flutter:
  uses-material-design: true
  assets:
     - assets/images/background.png
     - assets/images/logo.png

dev_dependencies:
  flutter_lints: ^5.0.0
 # flutter_native_splash: ^2.4.6
